version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-node

    working_directory: ~/osquery-live
    steps:
      - checkout

      # Test Go server
      - run: go vet ./...
      - run: go build -o backend ./server
      - run: go test -v ./...

      # Test JS frontend

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn lint
      - run: yarn test
